# Generated by Django 4.1.2 on 2022-10-28 06:32

from django.db import migrations

code_dict = {
    'name': 'Belarus',
    'code': 'blr',
}


def change_country_code(apps, schema_editor):
    new_name = code_dict.get('name')
    new_code = code_dict.get('code')

    query = apps.get_model("country", "Country")

    # using — псевдоним подключения к базе данных, который будет отличаться от
    # DEFAULT_DB_ALIAS при использовании нескольких баз данных.

    #  RunPython не может волшебным образом изменить соединение моделей для вас;
    #  все методы модели, которые вы вызываете, попадут в базу данных по умолчанию,
    #  если вы не предоставите им текущий псевдоним базы данных
    #  (доступно из schema_editor.connection.alias , где schema_editor - второй аргумент вашей функции)

    db_alias = schema_editor.connection.alias
    # db_alias = 'default'

    print(db_alias)
    # default

    # DATABASES = {
    #     "default": {
    #     ...............
    #     },
    #    'other_db': {
    #     ................
    #     },
    # }

    print(type(db_alias))
    # <class 'str'>
    for item in query.objects.using(db_alias).filter(name="France", code="fr"):
        item.name = new_name
        item.code = new_code
        item.save()


def revers_country_code(apps, schema_editor):
    old_name = 'France'
    old_code = 'fr'

    query = apps.get_model("country", "Country")
    db_alias = schema_editor.connection.alias
    for item in query.objects.using(db_alias).filter(name="Belarus", code="blr"):
        item.name = old_name
        item.code = old_code
        item.save()


class Migration(migrations.Migration):
    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(change_country_code, revers_country_code),
    ]
