# Generated by Django 4.1.2 on 2022-11-01 11:41

from django.db import migrations, models


def save_to_slug(apps, schema_editor):
    Product = apps.get_model('change_field', 'Product')
    for prod in Product.objects.all():
        slug_n, created = Product.objects.get_or_create(uuid_id=prod.uuid_id)
        temp = str(slug_n.uuid_id)
        temp_2 = temp.replace('-', '')
        prod.slug = temp_2
        prod.save()


class Migration(migrations.Migration):

    dependencies = [
        ('change_field', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.RunPython(save_to_slug),
    ]
