# Generated by Django 4.1.2 on 2022-11-01 11:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('change_field', '0002_product_slug'),
    ]

    operations = [

        migrations.AlterField(
            model_name='product',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, primary_key=True, serialize=False),
        ),

    ]
