# Generated by Django 4.1.2 on 2022-10-25 12:28

from django.db import migrations
from django.db import models

class Migration(migrations.Migration):

    def custom_task(self, schema_editor):
        my_model = self.get_model('my_app', 'MyModel')
        for item in my_model.objects.all():
            field_old_time = item.field_mame_time
            field_new_int = 12345
            item.field_name = field_new_int
            item.save()

    # datetimeobj = datetime(2000, 2, 3, 4, 5, 23)
    # total4 = int(datetimeobj.timestamp())

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='MyModel',
            old_name='field_name',
            new_name='field_name_old',
        ),
        migrations.AddField(
            model_name='MyModel',
            name='field_name',
            field=models.PositiveIntegerField(),
        ),
        migrations.RunPython(custom_task),
        migrations.RemoveField(
            model_name='MyModel',
            name='field_name_old',
        )
    ]