# Generated by Django 4.1.2 on 2022-10-27 13:42

from django.db import migrations


def link_artists(apps, schema_editor):
    Album = apps.get_model('my_app', 'Album')
    Artist = apps.get_model('my_app', 'Artist')
    for album in Album.objects.all():
        artist, created = Artist.objects.get_or_create(name=album.artist)
        album.artist_link = artist
        album.save()


class Migration(migrations.Migration):
    dependencies = [
        ('my_app', '0002_artist_album_artist_link'),
    ]

    operations = [
        migrations.RunPython(link_artists),
    ]
