# Generated by Django 4.1.2 on 2022-10-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
    ]
