# Generated by Django 4.1.2 on 2022-10-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_album_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_link',
            new_name='artist',
        ),
    ]
