# Generated by Django 4.1.2 on 2022-10-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug_new',
            field=models.SlugField(blank=True, max_length=32, null=True),
        ),
    ]
