# Generated by Django 4.1.2 on 2022-10-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_product_slug_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug_new',
            field=models.SlugField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
