# Generated by Django 4.1.2 on 2022-10-28 09:14

from django.db import migrations


def link_slug(apps, schema_editor):
    Product = apps.get_model('event', 'Product')
    for prod in Product.objects.all():
        slug_new, created = Product.objects.get_or_create(uuid_id=prod.uuid_id)
        prod.artist_link = slug_new
        prod.save()

    # class Product(models.Model):
    #     uuid_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    #     details = models.TextField(default='some text')
    #     slug = models.SlugField(blank=True, null=True)
    #     slug_new = models.SlugField(blank=True, null=True, max_length=32, unique=True)


class Migration(migrations.Migration):
    dependencies = [
        ('event', '0004_alter_product_slug_new'),
    ]

    operations = [
        migrations.RunPython(link_slug),
    ]
