# Generated by Django 4.1.2 on 2022-10-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_product_slug_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug_new',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
