# Generated by Django 4.1.2 on 2022-10-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_transfer_uuid_4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
