# Generated by Django 4.1.2 on 2022-11-01 10:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('details', models.TextField(default='some text')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
    ]
