# Generated by Django 4.1.2 on 2022-11-01 10:18

from django.db import migrations


def link_slug(apps, schema_editor):
    Product = apps.get_model('change_pk', 'Product')
    for prod in Product.objects.all():
        slug_n, created = Product.objects.get_or_create(uuid_id=prod.uuid_id)
        temp = str(slug_n.uuid_id)
        temp_2 = temp.replace('-', '')
        prod.slug = temp_2
        prod.save()


class Migration(migrations.Migration):
    dependencies = [
        ('change_pk', '0002_product_slug_new'),
    ]

    operations = [
        migrations.RunPython(link_slug),
    ]
