# Generated by Django 4.1.2 on 2022-11-01 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('change_pk', '0003_save_uuid_to_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uuid_id_new',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
