# Generated by Django 4.1.2 on 2022-11-01 10:31

from django.db import migrations
# Generated by Django 4.1.2 on 2022-11-01 10:21

from django.db import migrations


def link_slug(apps, schema_editor):
    Product = apps.get_model('change_pk', 'Product')
    for prod in Product.objects.all():
        slug_n, created = Product.objects.get_or_create(uuid_id=prod.uuid_id)
        temp = slug_n.uuid_id
        prod.uuid_id_new = temp
        prod.save()


class Migration(migrations.Migration):
    dependencies = [
        ('change_pk', '0004_product_uuid_id_new'),
    ]

    operations = [
        migrations.RunPython(link_slug),

    ]
