# Generated by Django 4.1.2 on 2022-11-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_pk', '0005_save_uuid_to_uuid_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uuid_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
