# Generated by Django 4.1.2 on 2022-11-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_pk', '0007_rename_uuid_id_new_product_uuid_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug_new',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, primary_key=True, serialize=False),
        ),
    ]
