# Generated by Django 4.1.2 on 2022-11-01 09:01

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_remove_post_id_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug_no',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
