# Generated by Django 4.1.2 on 2022-11-01 09:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0004_remove_post_slug_alter_post_uuid_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uuid_id2',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
