# Generated by Django 4.1.2 on 2022-11-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0005_post_uuid_id2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uuid_id',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug_no',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
